# Generated by Django 4.2.2 on 2023-07-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoBulletComment',
            fields=[
                ('bul_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='视频弹幕号')),
                ('bul_Comment', models.CharField(max_length=63, verbose_name='视频弹幕内容')),
                ('bul_PlayTime', models.CharField(max_length=255, verbose_name='视频弹幕播放时间')),
            ],
            options={
                'db_table': '视频弹幕表',
            },
        ),
        migrations.CreateModel(
            name='videoClass',
            fields=[
                ('class_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='分区号')),
                ('class_Name', models.CharField(max_length=255, verbose_name='分区名称')),
            ],
            options={
                'db_table': '视频分区表',
            },
        ),
        migrations.CreateModel(
            name='videoComment',
            fields=[
                ('com_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='视频评论编号')),
                ('comment', models.CharField(max_length=1023, verbose_name='视频评论')),
                ('com_Time', models.CharField(max_length=255, verbose_name='视频评论时间')),
            ],
            options={
                'db_table': '视频评论表',
            },
        ),
        migrations.CreateModel(
            name='videoTable',
            fields=[
                ('vid_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='视频号')),
                ('vid_Name', models.CharField(max_length=255, verbose_name='视频名称')),
                ('vid_Time', models.CharField(max_length=255, verbose_name='视频投稿时间')),
                ('vid_PlayNum', models.IntegerField(default=0, verbose_name='视频播放量')),
                ('vid_File', models.FileField(upload_to='video/', verbose_name='视频文件')),
                ('vid_CoverFile', models.ImageField(upload_to='video/', verbose_name='视频封面')),
                ('vid_Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSys.videoclass', verbose_name='视频分区')),
            ],
            options={
                'db_table': '视频表',
            },
        ),
        migrations.CreateModel(
            name='videoLikeFavorite',
            fields=[
                ('LF_id', models.AutoField(primary_key=True, serialize=False, verbose_name='视频点赞收藏编号')),
                ('Type', models.CharField(choices=[('like', '点赞'), ('favorite', '收藏')], max_length=255, verbose_name='视频点赞收藏类型')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='UserSys.user', verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSys.videotable', verbose_name='视频')),
            ],
            options={
                'db_table': '视频点赞收藏表',
            },
        ),
        migrations.CreateModel(
            name='videoContribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribute', to='UserSys.user', verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSys.videotable', verbose_name='视频')),
            ],
            options={
                'db_table': '视频投稿表',
            },
        ),
        migrations.CreateModel(
            name='videoCompilations',
            fields=[
                ('comp_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='视频合集号')),
                ('comp_Name', models.CharField(max_length=255, verbose_name='视频合集名称')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSys.videotable', verbose_name='视频')),
            ],
            options={
                'db_table': '视频合集表',
            },
        ),
        migrations.CreateModel(
            name='videoCommentPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='UserSys.user', verbose_name='用户')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSys.videocomment', verbose_name='评论')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSys.videotable', verbose_name='视频')),
            ],
            options={
                'db_table': '视频评论发送表',
            },
        ),
        migrations.CreateModel(
            name='videoBulletCommentPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet', to='UserSys.user', verbose_name='用户')),
                ('bulletcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSys.videobulletcomment', verbose_name='弹幕')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSys.videotable', verbose_name='视频')),
            ],
            options={
                'db_table': '视频弹幕发送表',
            },
        ),
        migrations.AddConstraint(
            model_name='videolikefavorite',
            constraint=models.UniqueConstraint(fields=('User', 'Type', 'video'), name='点赞收藏唯一性约束'),
        ),
        migrations.AddConstraint(
            model_name='videocontribute',
            constraint=models.UniqueConstraint(fields=('User', 'video'), name='投稿唯一性约束'),
        ),
        migrations.AddConstraint(
            model_name='videocommentpush',
            constraint=models.UniqueConstraint(fields=('User', 'video', 'comment'), name='评论唯一性约束'),
        ),
        migrations.AddConstraint(
            model_name='videobulletcommentpush',
            constraint=models.UniqueConstraint(fields=('User', 'video', 'bulletcomment'), name='弹幕唯一性约束'),
        ),
    ]
