# Generated by Django 4.2.2 on 2023-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=11, unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
