# Generated by Django 3.2.11 on 2023-07-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('Meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
                ('Meeting_Status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')])),
                ('Presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='UserSys.user')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('BanUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSys.user')),
            ],
        ),
    ]
