# Generated by Django 4.2.2 on 2023-07-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('Meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
                ('Meeting_Status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')])),
                ('Presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='UserSys.user')),
            ],
            options={
                'db_table': '会议表',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('BanUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSys.user')),
                ('MeetingRoom', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='MeetingSys.meeting')),
            ],
            options={
                'db_table': '黑名单表',
            },
        ),
    ]
