# Generated by Django 3.2.11 on 2023-07-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='MeetingRoom',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='MeetingSys.meeting'),
        ),
        migrations.AlterModelTable(
            name='blacklist',
            table='黑名单表',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='会议表',
        ),
    ]
