# Generated by Django 3.2.11 on 2023-07-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='用户',
        ),
    ]
