# Generated by Django 4.2.3 on 2023-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveSys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveroom',
            name='roomcover',
            field=models.ImageField(upload_to='livecover/', verbose_name='roomcover'),
        ),
    ]
